exports.SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
exports.SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
exports.ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
exports.SEND_ACTIVATION_EMAIL_SUCCESS = 'SEND_ACTIVATION_EMAIL_SUCCESS';
exports.SEND_RESET_PWD_EMAIL_SUCCESS = 'SEND_RESET_PWD_EMAIL_SUCCESS';
exports.PWD_CHANGED_SUCCESS = 'PWD_CHANGED_SUCCESS';
